invoice_number:
  - "Invoice No"
  - "Invoice Number"
  - "Invoice #"

invoice_date:
  - "Invoice Date"
  - "Date of Invoice"

due_date:
  - "Due Date"

seller_name:
  - "Seller"
  - "From"

buyer_name:
  - "Buyer"
  - "To"

currency:
  - "Currency"

